#!/bin/bash
set -x
cd $OPENSHIFT_DATA_DIR

if [ -d $OPENSHIFT_DATA_DIR/apache-tomcat-$OPENSHIFT_TOMCAT85_VERSION ]
then
    # Java 1.8 set env
    export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
    export PATH=$JAVA_HOME/bin:$PATH


	cd apache-tomcat-$OPENSHIFT_TOMCAT85_VERSION/bin
	./startup.sh
    exit 0
else
    # Java 1.8 Configuration
    cd $OPENSHIFT_DATA_DIR
    export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
    export PATH=$JAVA_HOME/bin:$PATH

	# Apache Tomcat installation
    cd $OPENSHIFT_DATA_DIR
    wget http://apache.claz.org/tomcat/tomcat-8/v8.5.11/bin/apache-tomcat-$OPENSHIFT_TOMCAT85_VERSION.tar.gz
    tar xzvf apache-tomcat-$OPENSHIFT_TOMCAT85_VERSION.tar.gz
    TOMCAT_HOME=$OPENSHIFT_DATA_DIR/apache-tomcat-$OPENSHIFT_TOMCAT85_VERSION
    export TOMCAT_HOME

	# configure tomcat
	cd $TOMCAT_HOME/conf/
	ip=$OPENSHIFT_DIY_IP
	sed -i "s#<Server\s*port=\(\"8005\"\)\(.*\)#<Server address=\"$ip\" port=\"18005\" \2#g" server.xml
	sed -i "s#<Connector\s*port=\(\"8080\"\)\(.*\)#<Connector address=\"$ip\" port=\"8080\" \2#g;" server.xml
	sed -i "s#<Connector\s*port=\(\"8009\"\)\(.*\)#<Connector address=\"$ip\" port=\"18009\" \2#g" server.xml
	sed -i "s#redirectPort=\"8443\"#redirectPort=\"18443\"#g" server.xml
	cd ../bin
	./startup.sh
fi
